version: "3.9"

services:
  api:
    build: .
    container_name: quotapilot-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: quotapilot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

